deployment:
  name1: nginx-deployment
  image1:
    repository: "gcr.io/google-samples"
    name: "hello-app"
    tag: "1.0"
  port1: 8080
  replicas1: 3
  name2: nginx-deployment2
  image2:
    repository: "gcr.io/google-samples"
    name: "hello-app"
    tag: "2.0"
  port2: 8080
  replicas2: 3

app:
  name1: nginx
  name2: nginx2


service:
  name1: my-service
  port1: 80
  name2: my-service2
  port2: 80
  protocol: TCP


ingress:
  name: minimal-ingress
  path1: /
  path2: /hello
  path_type: Prefix