apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  storageClassName: {{ .Values.pvc.storage_class_name }}
  accessModes:
    - {{ .Values.pvc.access_mode }}
  resources:
    requests:
      storage: {{ .Values.pvc.capacity }}				# claim PV with <this size