apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name1 }}
  labels:
    app: {{ .Values.app.name1 }}
spec:
  replicas: {{ .Values.deployment.replicas1 }}
  selector:
    matchLabels:
      app: {{ .Values.app.name1 }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name1 }}
    spec:
      containers:
      - name: {{ .Values.app.name1 }}
        image: "{{ .Values.deployment.image1.repository }}/{{ .Values.deployment.image1.name }}:{{ .Values.deployment.image1.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.port1 }}
