apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name2 }}
spec:
  selector:
    app: {{ .Values.app.name2 }}
  ports:
    - protocol: {{ .Values.service.protocol2 }}
      port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.deployment.port2 }}
