apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name1 }}
spec:
  selector:
    app: {{ .Values.app.name1 }}
  ports:
    - protocol: {{ .Values.service.protocol1 }}
      port: {{ .Values.service.port1 }}
      targetPort: {{ .Values.deployment.port }}
