apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service2_name }}
spec:
  selector:
    app: {{ .Values.app2_name }}
  ports:
    - protocol: {{ .Values.service_protocol }}
      port: {{ .Values.service2_port }}
      targetPort: {{ .Values.deploy2_port }}
