apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service1_name }}
spec:
  selector:
    app: {{ .Values.app_name }}
  ports:
    - protocol: {{ .Values.service_protocol }}
      port: {{ .Values.service1_port }}
      targetPort: {{ .Values.deploy1_port }}
